---
# defaults file for install-packages
pacotes8:
  - bc
  - elfutils-libelf
  - elfutils-libelf-devel
  - glibc
  - glibc-devel  
  - ksh
  - libaio
  - libaio-devel
  - libXrender  
  - libX11
  - libXau
  - libXi
  - libXtst
  - libgcc
  - libnsl  
  - librdmacm
  - libstdc++
  - libstdc++-devel
  - libxcb  
  - libibverbs  
  - make
  - policycoreutils
  - policycoreutils-python-utils
  - smartmontools  
  - binutils
  - sysstat  
  - tar  
  - vim
  - chrony  
  - fontconfig-devel
  - nfs-utils
  - net-tools
  - ntp
  - xorg-x11-utils
  - xorg-x11-xauth

pacotes7:
  - nspr
  - libstdc++*
  - libgcc*
  - libc*
  - glibc.i686
  - nfs-utils
  - net-tools
  - ntp
  - vim
  - psmisc
  - binutils
  - compat-libcap1
  - compat-libstdc++-33
  - gcc
  - gcc-c++
  - glibc
  - glibc-devel
  - ksh
  - libgcc
  - libstdc++
  - libstdc++-devel
  - libaio
  - libaio-devel
  - libXext
  - libXtst
  - libX11
  - libXau
  - libxcb
  - libXi
  - make
  - sysstat
  - libXmu
  - libXt
  - libXv
  - libXxf86dga
  - libdmx
  - libXxf86misc
  - libXxf86vm
  - xorg-x11-utils
  - xorg-x11-xauth

