---
- name: Desabilita SELinux
  selinux:
   state: disabled
  notify:
  - restart host

- name: Desabilita servico Firewalld
  systemd:
    name: firewalld
    enabled: no
    masked: yes

- name: Para servico Firewalld
  systemd:
    name: firewalld
    state: stopped

- name: del users "oracle" "grid"
  user: 
    name: "{{item}}"
    state: absent
    remove: yes
  loop:
    - oracle
    - grid 

- name: del groups
  group: 
    name: "{{item}}"
    state: absent
  loop:
    - oinstall
    - asmadmin
    - asmdba
    - asmoper
    - dba
    - oper
    - oracle

- name:  add groups
  group: 
    name: "{{ item.name }}"
    gid: "{{ item.gid }}" 
    state: present
  loop:
    - { name: "oinstall", gid: "54321" }
    - { name: "asmadmin", gid: "54329" }
    - { name: "asmdba", gid: "54327" }
    - { name: "asmoper", gid: "54328" }
    - { name: "dba", gid: "54322" }
    - { name: "oper", gid: "54323" }
    - { name: "backupdba", gid: "54324" }
    - { name: "dgdba", gid: "54325" }
    - { name: "kmdba", gid: "54326" }


- name: add user "oracle" uid=54321
  user: uid=54321 name=oracle group=oinstall home=/home/oracle groups=dba,oper,asmdba,asmadmin,asmoper password="qwe123" force=yes

- name: add user "grid" uid=54322
  user: uid=54322 name=grid group=oinstall home=/home/grid groups=asmadmin,asmdba,asmoper,dba password="qwe123" force=yes

- name: Cria GRID_BASE
  file: path=/u01/app/grid state=directory

- name: Cria GRID_HOME
  file: path=/u01/app/19/grid state=directory

- name: Cria ORACLE_HOME
  file: path=/u01/app/oracle/product/19/dbhome_1 state=directory

- name: Altera owner, grupo e modo para o diretorio /u01
  file: path=/u01 owner=grid group=oinstall mode=0775 recurse=yes

- name: Altera owner e grupo para o diretorio /u01/app/oracle
  file: path=/u01/app/oracle owner=oracle group=oinstall mode=0775 recurse=yes

